#+TITLE: Sean Brage's Emacs Configuration
#+AUTHOR: Sean Brage
#+EMAIL: seanmbrage@me.com
* My Emacs Configuration
Configuring Emacs is a lifelong, personal, rewarding, and frustrating
pursuit. It's easy to go overboard from the start, adding packages and
tweaks all over the place.

My configuration is tailored around a few key principles:

1. Emacs is fast. Keep it that way.
2. Don't install a third-party tool when a built-in one exists,
   *unless* you have a very good reason for doing so.
3. Spend your time working on the work, not working on the tools.
4. Don't use a tool if you don't understand what it's doing (and
   how). Eliminate "black magic" from your toolbelt.

In pursuit of these goals, I try very hard to run a "lean"
configuration. I *like* the default Emacs keybindings for navigating
and editing text, so you won't find things like Evil. =M-x= + a few
letters isn't that much of a time-waster, so I don't have a ton of
custom key mappings. All-in-all, I'm aiming to be familiar with Emacs
itself, and good at doing my daily work in it.
